import { NextResponse } from "next/server";
import { z } from "zod";
import { upsertPage } from "@/lib/confluence.server";
import { getTestPlan, getTestRun, listTestCases } from "@/data/store";
import { logger } from "@/lib/logger";

const publishSchema = z.object({
  kind: z.enum(["plan", "run", "coverage"]),
  id: z.string().min(1).optional(),
});

function escHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

async function buildPlanHtml(id: string): Promise<{ title: string; html: string }> {
  const plan = await getTestPlan(id);
  if (!plan) throw new Error(`TestPlan ${id} not found`);
  const cases = await listTestCases();
  const planCases = cases.filter((c) => plan.testCaseIds.includes(c.id));
  const rows = planCases
    .map(
      (c) =>
        `<tr><td>${escHtml(c.id)}</td><td>${escHtml(c.title)}</td><td>${escHtml(c.status)}</td><td>${escHtml(c.priority)}</td><td>${escHtml(c.owner)}</td></tr>`,
    )
    .join("");
  const title = `[Weave] Plan: ${plan.name}`;
  const html = `<h1>${escHtml(plan.name)}</h1>
<p>${escHtml(plan.description || "")}</p>
<p>Generated by Theridion Weave at ${new Date().toISOString()}</p>
<table>
  <thead><tr><th>ID</th><th>Title</th><th>Status</th><th>Priority</th><th>Owner</th></tr></thead>
  <tbody>${rows}</tbody>
</table>`;
  return { title, html };
}

async function buildRunHtml(id: string): Promise<{ title: string; html: string }> {
  const run = await getTestRun(id);
  if (!run) throw new Error(`TestRun ${id} not found`);
  const passCount = run.results.filter((r) => r.status === "pass").length;
  const failCount = run.results.filter((r) => r.status === "fail").length;
  const total = run.results.length;
  const rows = run.results
    .map(
      (r) =>
        `<tr><td>${escHtml(r.testId)}</td><td>${escHtml(r.title)}</td><td>${escHtml(r.status)}</td><td>${r.durationMs}ms</td><td>${escHtml(r.notes ?? "")}</td></tr>`,
    )
    .join("");
  const title = `[Weave] Run: ${run.label ?? run.id}`;
  const html = `<h1>${escHtml(run.label ?? run.id)}</h1>
<p><strong>Source:</strong> ${escHtml(run.source)} | <strong>Triggered by:</strong> ${escHtml(run.triggeredBy)}</p>
<p><strong>Results:</strong> ${passCount}/${total} pass, ${failCount} fail</p>
<p>Generated by Theridion Weave at ${new Date().toISOString()}</p>
<table>
  <thead><tr><th>Test ID</th><th>Title</th><th>Status</th><th>Duration</th><th>Notes</th></tr></thead>
  <tbody>${rows}</tbody>
</table>`;
  return { title, html };
}

async function buildCoverageHtml(): Promise<{ title: string; html: string }> {
  const cases = await listTestCases();
  const active = cases.filter((c) => c.status === "active");
  const title = `[Weave] Coverage Report`;
  const rows = active
    .map((c) => `<tr><td>${escHtml(c.id)}</td><td>${escHtml(c.title)}</td><td>${escHtml(c.status)}</td></tr>`)
    .join("");
  const html = `<h1>Test Coverage Report</h1>
<p>Active cases: ${active.length} / Total: ${cases.length}</p>
<p>Generated by Theridion Weave at ${new Date().toISOString()}</p>
<table>
  <thead><tr><th>ID</th><th>Title</th><th>Status</th></tr></thead>
  <tbody>${rows}</tbody>
</table>`;
  return { title, html };
}

export async function POST(req: Request) {
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Neplatný JSON" }, { status: 400 });
  }

  const parsed = publishSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "Validace selhala", issues: parsed.error.flatten() }, { status: 422 });
  }

  try {
    let title: string;
    let html: string;

    if (parsed.data.kind === "plan") {
      if (!parsed.data.id) return NextResponse.json({ error: "id is required for kind=plan" }, { status: 422 });
      ({ title, html } = await buildPlanHtml(parsed.data.id));
    } else if (parsed.data.kind === "run") {
      if (!parsed.data.id) return NextResponse.json({ error: "id is required for kind=run" }, { status: 422 });
      ({ title, html } = await buildRunHtml(parsed.data.id));
    } else {
      ({ title, html } = await buildCoverageHtml());
    }

    const result = await upsertPage(title, html);
    return NextResponse.json(result, { status: 200 });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    logger.error("POST /api/confluence/publish failed", e);
    if (msg.includes("disabled") || msg.includes("configured")) {
      return NextResponse.json({ error: msg }, { status: 409 });
    }
    if (msg.includes("not found")) {
      return NextResponse.json({ error: msg }, { status: 404 });
    }
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
